# Generated by Django 3.2.7 on 2021-09-18 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addresses',
            new_name='Account',
        ),
    ]
