# Generated by Django 3.2.7 on 2021-09-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_addresses_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='address',
        ),
        migrations.AddField(
            model_name='account',
            name='affiliated_unit',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='rank',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='serial_number',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
