# Generated by Django 3.2.7 on 2021-09-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210919_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='permission',
            field=models.IntegerField(default=2),
        ),
    ]
