# Generated by Django 3.2.7 on 2021-09-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_permission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='serial_number',
            new_name='military_id',
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(default='', max_length=30),
        ),
    ]
