# Generated by Django 3.2.7 on 2021-10-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firearm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firearm',
            name='opType',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='firearm',
            name='SerialNumber',
            field=models.CharField(max_length=30),
        ),
    ]
