# Generated by Django 3.2.7 on 2021-10-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firearm', '0004_auto_20211012_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firearm',
            name='Owner',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
