http://localhost:8080/fooddata/

###

http://localhost:8080/fooddata/blocks

###

POST http://localhost:8080/fooddata/blocks

###

http://localhost:8080/blocks/fooddata/{hash}

###
http://localhost:8080/fooddata/transactions/delivery/1stBrigade/1stGeneration/Kimchi/280
###
http://localhost:8080/fooddata/transactions/delivery/11/111/Kimchi/150
###
http://localhost:8080/fooddata/transactions/delivery/11/112/Kimchi/50

###

http://localhost:8080/fooddata/transactions/provide/1/Kimchi/750

###
http://localhost:8080/fooddata/transactions/mempool

###

http://localhost:8080/fooddata/transactions/balance/11/Kimchi

###

http://localhost:8080/fooddata/2021-09-21/Kimchi