# Generated by Django 3.2.7 on 2021-10-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opType', models.TextField()),
                ('Affiliated_Unit', models.TextField(default='-')),
                ('FoodName', models.TextField(default='-')),
                ('Amount', models.TextField(default='-')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
