http://localhost:8080/fooddata
//사용법 보기

###

///튜토리얼 시작
// 이해심화를 위해 1)을 한 후와 3)을 한 후 test.http 파일 맨 아래에 있는 mempool보기를 사용할 수 있음

http://localhost:8080/fooddata/admin/provide/1stBrigade/Kimchi/750
//1) 1stBrigade에 750만큼의 김치를 제공(초기 제공, 관리자 권한)
###

POST http://localhost:8080/fooddata/admin/approve
//2) mempool에 있는 데이터 생성 승인 (관리자 권한)

###
http://localhost:8080/fooddata/makefooddata/Kimchi/1stBrigade/1stGeneration/280
//3) 1stBrigade에서 1stGeneration로 280만큼의 김치를 전달한다는 트랜잭션 생성 (일반 권한)

###

POST http://localhost:8080/fooddata/admin/approve
//4) mempool에 있는 데이터 생성 승인 (관리자 권한)

###

http://localhost:8080/fooddata/see/2021-09-25/Kimchi
//5) 2021-09-25에 김치에 대한 부식작전 현황 보기(일반 권한)
//  날짜는 자동생성이기 때문에 테스트를 진행하는 당일 날짜로 바꿔서 진행바람

//튜토리얼 종료

###

http://localhost:8080/fooddata/admin/mempool
// mempool보기(아직 user용으로 다듬어지지 않음. 추후 관리자 계층이 아직 승인되지 않은 데이터를 확인하기 위한 용도로 수정할 예정) (관리자 권한)