# Generated by Django 3.2.7 on 2021-10-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firearm', '0002_auto_20211008_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firearm',
            name='Misc',
            field=models.TextField(default=''),
        ),
    ]
